### ISSUE TITLE
Function to pull metadata from description file

### ISSUE THREAD

**Issue by collinschwantes** [ropenscilabs/deposits#16]
Users may already be creating much of the necessary metadata for submission in a description file. It would be convenient to be able to pull the fields that map appropriately from the description file to the metadata file.

**Comment by mpadge** [comment]
Do you mean the `DESCRIPTION` file of an R (or, equivalently Debian) package? Or something else?

**Comment by collinschwantes** [comment]
Revisiting our discussion from a couple of months ago - I was thinking that this would be from the `DESCRIPTION` file of a package.

**Comment by mpadge** [comment]
I'll be devoting a lot more time to this package from this month on, so you should see commits appearing here soon.

**Comment by mpadge** [comment]
@collinschwantes I quickly whipped this together today, because i need it for my own further development. Current functionality looks somethings liket this, as tested on [this Zenodo release of one of my packages](https://zenodo.org/record/5731467):

``` r
library (deposits)
packageVersion ("deposits")
#> [1] '0.2.0.37'
service <- "zenodo"
cli0 <- depositsClient$new (service = service, sandbox = FALSE)
id <- 5731467
cli0$deposit_retrieve (id)
```

That deposit was generated directly by Zenodo's GitHub integration, with the metadata looking like this:
``` r
cli0$hostdata$metadata
#> $access_right
#> [1] "open"
#> 
#> $communities
#>   identifier
#> 1     zenodo
#> 
#> $creators
#>                     affiliation            name
#> 1                     @rOpenSci    mark padgham
#> 2 Australian Antarctic Division  Michael Sumner
#> 3                          <NA> Nicholas Potter
#> 
#> $description
#> [1] "<p>Fixes CRAN checks on Solaris machines</p>"
#> 
#> $doi
#> [1] "10.5281/zenodo.5731467"
#> 
#> $license
#> [1] "other-open"
#> 
#> $prereserve_doi
#> $prereserve_doi$doi
#> [1] "10.5281/zenodo.5731467"
#> 
#> $prereserve_doi$recid
#> [1] 5731467
#> 
#> 
#> $publication_date
#> [1] "2021-11-27"
#> 
#> $related_identifiers
#>                                           identifier       relation scheme
#> 1 https://github.com/ropensci/mapscanner/tree/v0.0.6 isSupplementTo    url
#> 
#> $title
#> [1] "ropensci/mapscanner: CRAN version 0.0.06"
#> 
#> $upload_type
#> [1] "software"
#> 
#> $version
#> [1] "v0.0.6"
cli0$hostdata$files [, 1:4]
#>                           checksum                       filename filesize
#> 1 02e48138ddb5de28a5350595dd66a9d1 ropensci/mapscanner-v0.0.6.zip  1728938
#>                                     id
#> 1 a4b2f84d-6d81-4c49-8265-786a76e08d42
```

Note that the uploaded version is compressed as a zip archive, which can not be changed to any other format. This is then the equivalent workflow in deposits:

``` r
path <- "/<local>/<path>/<to>/ropensci/mapscanner"
cli <- depositsClient$new (service = service, sandbox = TRUE, metadata = path)
cli$deposit_new ()
#> ID of new deposit : 1203848

# A couple of minor tweaks to improve printed output of metadata:
cli$hostdata$metadata$creators <- data.frame (do.call (rbind, cli$hostdata$metadata$creators))
cli$hostdata$metadata$notes <- NULL

cli$hostdata$metadata
#> $access_right
#> [1] "closed"
#> 
#> $creators
#>                name
#> 1      Mark Padgham
#> 2 Michael D. Sumner
#> 
#> $description
#> [1] "Enables preparation of maps to be printed and drawn on.\\nModified maps can then be scanned back in, and hand-drawn marks\\nconverted to spatial objects."
#> 
#> $doi
#> [1] ""
#> 
#> $prereserve_doi
#> $prereserve_doi$doi
#> [1] "10.5072/zenodo.1203848"
#> 
#> $prereserve_doi$recid
#> [1] 1203848
#> 
#> 
#> $publication_date
#> [1] "2023-05-17"
#> 
#> $title
#> [1] "Print Maps, Draw on Them, Scan Them Back in"
#> 
#> $upload_type
#> [1] "software"
#> 
#> $version
#> [1] "0.0.6.004"
```

Differences to the GitHub-triggered metadata are:

- the  GitHub-triggered version has a "related_identifiers" containing the GitHub repo. That obviously can't be done in any reliable way for deposits, so that's okay.
- The title of the GitHub-triggered version is *not* the title of the actual package, rather it's just mashed together as a version title from `<org>/<repo>: <release_tag>`. The title via deposits can be artitrarily specified, with current version just taken straight from "DESCRIPTION" file.
- The creators entry of the GitHub-triggered version is wrong, and includes on listed person who is a reviewer and not an actual author; the deposits version correctly lists only those attributed authorial roles.
- The license field of the GitHub-triggered version fails to pick up the actual license, and instead lists a default and generic "other-open", whereas the deposits version lists the license correctly.

---

This final bit demonstrates the one-line upload of entire package code in specified format, where "tar" called on an R package bundles it "properly" via `pkgbuild`:

``` r
cli$deposit_upload_file (compress = "tar")
#> Loading required namespace: pkgbuild
#> ── R CMD build ─────────────────────────────────────────────────────────────────
#> * checking for file ‘/tmp/RtmppBRbeu/deposits_temppath_110ddd4d68ba/mapscanner/DESCRIPTION’ ... OK
#> * preparing ‘mapscanner’:
#> * checking DESCRIPTION meta-information ... OK
#> * cleaning src
#> * checking for LF line-endings in source and make files and shell scripts
#> * checking for empty or unneeded directories
#> Removed empty directory ‘mapscanner/data-raw’
#> Removed empty directory ‘mapscanner/man/figures’
#> Removed empty directory ‘mapscanner/tests/testthat/_snaps’
#> Omitted ‘LazyData’ from DESCRIPTION
#> * building ‘mapscanner_0.0.6.004.tar.gz’
print (cli)
#> <deposits client>
#>  deposits service : zenodo
#>            sandbox: TRUE
#>          url_base : https://sandbox.zenodo.org/api/
#>  Current deposits : 1 (see 'deposits' element for details)
#> 
#> url_service : https://sandbox.zenodo.org/deposit/1203848
#>  deposit id : 1203848
#>    hostdata : list with 14  elements
#>    metadata : 6 terms (see 'metadata' element for details)
#>  local_path : /<local>/<path>/<to>/ropensci/mapscanner
#>   resources : 0 local, 1 remote
cli$hostdata$files [, 1:4]
#>                           checksum                    filename filesize
#> 1 f47de482d3c64a83d901ad3ebca646a9 mapscanner_0.0.6.004.tar.gz  2581066
#>                                     id
#> 1 caa8327a-894c-4e91-a6ef-64317ef0f6af
```

**Comment by mpadge** [comment]
Closing this there. It will now provide a good general template for developing  #77, and may need to be re-visited as part of that.

**Comment by mpadge** [comment]
Re-opening to get this working for Figshare
